### ISSUE TITLE
Tracking from webcam 

### ISSUE THREAD

**Issue by shersoni610** [facebookresearch/co-tracker#11]
Hello,

instead of using recorded videos, is it possible to track items from the camera feed in real time?

Thanks

**Comment by nikitakaraevv** [comment]
Hi @shersoni610! Yes, it should be possible. We plan to add a demo with real-time tracking, but I don't have a specific timeline. Thanks for your understanding!

**Comment by liruiw** [comment]
Same question here.

**Comment by troveski** [comment]
Do we already have the demo with real-time tracking? @nikitakaraevv
