### ISSUE TITLE
CoTracker3 comparison with BootsTAPIR

### ISSUE THREAD

**Issue by serycjon** [facebookresearch/co-tracker#112]
Hi,

thanks for releasing CoTracker3 and congratulations for a cool new version.

For a fair comparison with BootsTAPIR, could you please specify the framerate of the "100,000 videos of 30 seconds each"?
How many **frames** are there in total in the training dataset? How does that compare to the 15M **24 frames long clips** used in BootsTAPIR?

Also regarding the BootsTAPIR - did you try some of the methods for data curation / preprocessing used in that paper?
I would assume it could lead to more meaningful improvement in CoTracker performance (TAPIR vs BootsTAPIR is +7% in the last column of CoTracker3 Tab. 1, while CoTracker3-kub-online vs CoTracker3-kub+15k-online is only +1%; similarly in Tab. 2 BootsTAPIR +4.8%, CoTracker3 only +2.8%).

**Comment by nikitakaraevv** [comment]
Hi @serycjon, we train the mode on sequences of 64 or 80 frames, depending on the model, as we describe in section "Implementation details" in Appendix. 30 seconds (900 frames) is the upper bound, most videos are around 10 seconds (300 frames), while some videos are no longer than 3 seconds. There's only one action happening in each video, and there's not much additional information beyond this action. So it doesn't matter that much whether it is 64 / 80 or 300 frames. CoTracker3 outperforms BootsTAPIR even after training on 15k or even fewer videos. 

The point of the paper is to show that it is possible to improve performance without additional data curation / processing by just training with multiple synthetic-trained teachers. Yes, additional augmentations would improve the performance of the model even more, but it would make the scaling pipeline more complicated. 

The baseline model is already quite strong, and we train it with teachers not stronger than the model itself. We also don't add additional layers during training.

**Comment by serycjon** [comment]
Hi @nikitakaraevv ,
thanks for the clarification, didn't notice the details in the appendix.
I find the improvement in performance quite low, but in the realm of self-supervised / unsupervised training even a small improvement is very nice.

> we train it with teachers not stronger than the model itself.

Yeah, this is very nice.

Looking forward to experimenting with CoTracker3.
