### ISSUE TITLE
Is it possible to analyze videos in real-time simultaneously using both online and offline modes?

### ISSUE THREAD

**Issue by Banboo-glich** [facebookresearch/co-tracker#115]
Thank you very much for your development of CoTracker3!

I have one question: Is it possible to analyze videos in real-time simultaneously using both online and offline modes?

I look forward to your reply

**Comment by nikitakaraevv** [comment]
Hi @Banboo-glich, thanks for the question! The offline model takes the entire video as input. It is possible as long as you provide it access to all the frames you need to analyse from the very beginning

**Comment by Banboo-glich** [comment]
Thank you for your  informative response! 
 I appreciate you clarifying how the offline model works with the entire video input. This helps me understand the capabilities and requirements of CoTracker3 better. Your explanation is very helpful for my project planning.
  Thanks again for your support and for developing such a useful tool!
