### ISSUE TITLE
Inquiry About Mask Parameter Support in Online

### ISSUE THREAD

**Issue by AlanxChen** [facebookresearch/co-tracker#136]
Hello, thank you for this great project. I currently have a question: does the online mode support adding a mask parameter?

The video I need to process is relatively long, but the camera position is fixed. Is this possible to implement?

**Comment by AlanxChen** [comment]
Have solved,Thx

**Comment by Moreland-cas** [comment]
> Hello, thank you for this great project. I currently have a question: does the online mode support adding a mask parameter?
> 
> The video I need to process is relatively long, but the camera position is fixed. Is this possible to implement?

How did you solve the mask parameter?
