### ISSUE TITLE
How to download FastCapture?

### ISSUE THREAD

**Issue by chongweiliu** [facebookresearch/co-tracker#19]
Thank you for your amazing work! But when I want to reproduce it on my own computer I realize I can't find the download link for FastCapture. Could you please provide more details about how to download FastCapture?

**Comment by nikitakaraevv** [comment]
Hi @chongweiliu, thank you! 
FastCapture is a benchmark based on [ZJU-MoCap](https://chingswy.github.io/Dataset-Demo/) and was provided to us by the authors of [this paper](https://arxiv.org/abs/2303.11898). 
If you want to download ZJU-MoCap, you will need to contact the authors of the dataset, as described [here](https://github.com/zju3dv/neuralbody/blob/master/INSTALL.md). It's a relatively small and difficult-to-setup benchmark, so I would recommend reproducing results on BADJA and TAP-Vid first.

**Comment by chongweiliu** [comment]
> Hi @chongweiliu, thank you! FastCapture is a benchmark based on [ZJU-MoCap](https://chingswy.github.io/Dataset-Demo/) and was provided to us by the authors of [this paper](https://arxiv.org/abs/2303.11898). If you want to download ZJU-MoCap, you will need to contact the authors of the dataset, as described [here](https://github.com/zju3dv/neuralbody/blob/master/INSTALL.md). It's a relatively small and difficult-to-setup benchmark, so I would recommend reproducing results on BADJA and TAP-Vid first.

Thank you for your reply. I will first try BADJA and TAP-Vid, and then follow your steps to download FastCapture.
