### ISSUE TITLE
eval_utils.py contains a bug propagated from evaluation_datasets.py

### ISSUE THREAD

**Issue by cdoersch** [facebookresearch/co-tracker#20]
Sorry I messed this one up.  Your numbers should get better if you apply the fix :-)

https://github.com/deepmind/tapnet/issues/34

**Comment by nikitakaraevv** [comment]
The bug is fixed in https://github.com/facebookresearch/co-tracker/commit/cd226f3e6f46916b533ff870cc5e4d9671a3c00a
