### ISSUE TITLE
Huggingface Spaces Demo

### ISSUE THREAD

**Issue by hugoycj** [facebookresearch/co-tracker#22]
I have created a demo of this repository using Hugging Face Spaces. The demo can be accessed [here](https://huggingface.co/spaces/chongjie/co-tracker_MVP) with the [source code](https://github.com/hugoycj/co-tracker_MVP). If someone is interested, they can try it out or deploy it on their own machine.
![Screenshot from 2023-08-17 01-46-29](https://github.com/facebookresearch/co-tracker/assets/40767265/1da32db3-af3a-4469-861e-0a7eba9d6ff2)

**Comment by osanseviero** [comment]
Very nice :fire:
