### ISSUE TITLE
Error when loading model using torch.hub

### ISSUE THREAD

**Issue by julkaztwittera** [facebookresearch/co-tracker#29]
Every time I try to load the model using the instruction from `Readme.md` using torch.hub, I get such an error:

```
torch/hub/facebookresearch_co-tracker_master/cotracker/models/core/cotracker/blocks.py", line 237, in <lambda>
    approx_gelu = lambda: nn.GELU(approximate="tanh")
TypeError: __init__() got an unexpected keyword argument 'approximate'
```

**Comment by wshjtuk** [comment]
how did you solve this problem

**Comment by justy93** [comment]
Hello, I have the same error trying to initialize the model. Has anyone came across this and was able to solve it? Thank you

**Comment by ZhanxyR** [comment]
Use torch>=1.12.
(see [here](https://pytorch.org/docs/1.12/generated/torch.nn.GELU.html?highlight=gelu#torch.nn.GELU))
