### ISSUE TITLE
RuntimeError: Invalid buffer size

### ISSUE THREAD

**Issue by horsto** [facebookresearch/co-tracker#38]
For relatively simple and short videos (in my case, for example w: 1944, h: 1944, frame number: 1680) I am getting errors like `RuntimeError: Invalid buffer size: 70.96 GB`. I presume this is because the whole video is loaded at once. 
Is there an obvious solution to loading and processing larger video files? 

I did stumble over @whymatter https://github.com/facebookresearch/co-tracker/compare/main...whymatter:co-tracker:streaming - this might be a solution? However, without diving into that code: When loading chunks, how are the transitions handled in between frame buffers?

**Comment by nikitakaraevv** [comment]
Hi @horsto, we're currently working on a new, improved version of CoTracker that will also support loading chunks of videos. We are planning to release it in late November. Predictions on live videos are also discussed in issue https://github.com/facebookresearch/co-tracker/issues/37.

**Comment by horsto** [comment]
That sounds great, I can't wait!
