### ISSUE TITLE
How to get weights for CPU support? (M1 Mac support)

### ISSUE THREAD

**Issue by bharat787** [facebookresearch/co-tracker#42]
Hi, 

Thanks for the great work! I was trying to implement the [SAM-PT](https://github.com/SysCV/sam-pt/tree/main) project with co-tracker and downloaded the co-tracker [model weights](https://github.com/facebookresearch/co-tracker/tree/main#download-model-weights). But I keep running into the error `AssertionError: Torch not compiled with CUDA enabled` on my M1 MacBook machine.

Is there a way to get the weights running on for CPU-only support? They seem to be hardcoded. (I did go through issue #9, but the suggestion there seems to be if I'm running co-tracker demo on local, although here for SAM-PT, I'm just trying to use the weights).

Thanks for the help!

**Comment by nikitakaraevv** [comment]
Hi @bharat787, thank you! I see you've opened a pull request  https://github.com/facebookresearch/co-tracker/pull/43.
I assume this fixes the problem?

**Comment by bharat787** [comment]
Hi, yes it does. Thanks for the merge!
