### ISSUE TITLE
Use cotracker_stride_8_wind_16.pth And 6 frames get bad result

### ISSUE THREAD

**Issue by Aatroy** [facebookresearch/co-tracker#45]
model: cotracker_stride_8_wind_16.pth
I modify the function named read_video_from_path in demo.py , just append 6 frames to video.
Then , I run the demo.py and print(pred_tracks), get the result below:
`

 tensor([[[[465., 180.]],

         [[  0.,   0.]],

         [[  0.,   0.]],

         [[  0.,   0.]],

         [[  0.,   0.]],

         [[  0.,   0.]]]], device='cuda:0')
`
It seems no track result.

But when I append 10 frames to video , the result it's ok .
`    
    video = read_video_from_path(args.video_path)
    points = torch.tensor([[0.,465.,180.]])

    if torch.cuda.is_available():
        points = points.cuda()
    video = torch.from_numpy(video).permute(0, 3, 1, 2)[None].float()

    model = CoTrackerPredictor(checkpoint=args.checkpoint)
    model = model.to(DEFAULT_DEVICE)
    video = video.to(DEFAULT_DEVICE)

    pred_tracks, pred_visibility = model(
        video,
        queries=points[None]
    )
    print(pred_tracks)
    print("computed")`

**Comment by nikitakaraevv** [comment]
Hi @Aatroy, thank you for the question! This issue was discussed here: https://github.com/facebookresearch/co-tracker/issues/40
