### ISSUE TITLE
Chinese newbie seeking help! Encountering issues while trying to install libraries using pip!

### ISSUE THREAD

**Issue by Eckes69** [facebookresearch/co-tracker#52]
![QQ图片20231219151918](https://github.com/facebookresearch/co-tracker/assets/89568536/cf26afa3-37aa-4df6-95c5-e15757603c42)

Python version is 3.10, changing proxy servers and sources did not work.

**Comment by Benjamin-So** [comment]
Hi! How did you solve this?
