### ISSUE TITLE
Inference with sequence of multiple images for a particular single pixel using co-tracker2

### ISSUE THREAD

**Issue by pknmax** [facebookresearch/co-tracker#59]
How to do inference with sequence of multiple images for a particular single pixel?
Is there a way to select this pixel in first image?

**Comment by nikitakaraevv** [comment]
Hi @pknmax, please see the "Tracking manually selected points" section  in the [Colab Demo](https://colab.research.google.com/github/facebookresearch/co-tracker/blob/main/notebooks/demo.ipynb) to see how to do it. Note that tracking individual points works best with [support point grids](https://github.com/facebookresearch/co-tracker/blob/9921cf0895b5eccf57666f3652e298a04646bcd3/cotracker/predictor.py#L51) , which are used by default in the `CoTrackerPredictor` and discarded at the output.

**Comment by nikitakaraevv** [comment]
Hi @pknmax, the model works for such pixels in some cases, but not always.
