### ISSUE TITLE
Question About GPU Memory Requirements for Model Training

### ISSUE THREAD

**Issue by sinkers-lan** [facebookresearch/co-tracker#65]
Hi, thanks for your inspiring work.

I am attempting to train thte model using an NVIDIA GeForce RTX 3090 GPU, which has approximately 24 GB of VRAM. However, I am encountering a "CUDA out of memory" issue, causing the training process to terminate prematurely.

what is the typical amount of VRAM required for successful training?

**Comment by nikitakaraevv** [comment]
Hi @sinkers-lan, you can reduce the number of tracks during training from 768 to 324 or 256 by passing `--traj_per_sample 256` as an [argument](https://github.com/facebookresearch/co-tracker?tab=readme-ov-file#training).

**Comment by sinkers-lan** [comment]
thanks for your nice reply

**Comment by qsisi** [comment]
> Hi @sinkers-lan, you can reduce the number of tracks during training from 768 to 324 or 256 by passing `--traj_per_sample 256` as an [argument](https://github.com/facebookresearch/co-tracker?tab=readme-ov-file#training).

Hello! @nikitakaraevv @sinkers-lan  Does reducing the number of tracks affect the final performance?

**Comment by nikitakaraevv** [comment]
Hi @qsisi, reducing the number of tracks to 384 doesn't seem to affect the performance at all. I don't know whether 324 or 256 tracks is worse than 384, likely not.

**Comment by nikitakaraevv** [comment]
@qsisi Could you try to reduce correlation radius to 2? Would this help? It shouldn't affect the performance that much.
https://github.com/facebookresearch/co-tracker/blob/9ed05317b794cd177674e681321780614a65e073/cotracker/models/core/cotracker/cotracker.py#L118

**Comment by qsisi** [comment]
@nikitakaraevv setting the radius=2 and input_dim=360 seems not really affect the gpu memory consumption... 
radius=3, input_dim=456:
![image](https://github.com/facebookresearch/co-tracker/assets/44374058/b897316a-11e0-4a6b-a0e4-1353553b3e67)
radius=2, input_dim=360:
![image](https://github.com/facebookresearch/co-tracker/assets/44374058/3b5072cc-ed08-454c-8bf4-55f494c624b3)

**Comment by qsisi** [comment]
@nikitakaraevv Hello! I also want to know the intuition behind the attention_mask & track_mask in training, could you please elaborate on that?  :)

Thanks!

**Comment by nikitakaraevv** [comment]
Hi @qsisi, we need attention masks to start tracking only from the window where the point is queried so that the model is not trying to track a point that will be queried in the future (this point can be invisible, but it also just hurts performance). The way it works is the model simply doesn't attend to points that will be queried in future windows.

Track masks serve the same purpose, but they localise the queried frame inside a window. However, I think they are not really needed, and can be safely removed :)

**Comment by nikitakaraevv** [comment]
@qsisi I see, setting `radius=2` mostly helps at inference (reduces peak gpu consumption by 2), but there's another trick that should help. 

For training, you can try two things:
1. Train in bf16: set `precision="bf16"` here:
```
https://github.com/facebookresearch/co-tracker/blob/9ed05317b794cd177674e681321780614a65e073/train.py#L612
```
2. Replace this line:
https://github.com/facebookresearch/co-tracker/blob/9ed05317b794cd177674e681321780614a65e073/cotracker/models/core/cotracker/cotracker.py#L261
by 
```
fmaps = torch.utils.checkpoint.checkpoint(self.fnet, video.reshape(-1, C, H, W),use_reentrant=False).reshape(
                B, -1, self.latent_dim, H // self.stride, W // self.stride
            )
```
 and this line:
https://github.com/facebookresearch/co-tracker/blob/9ed05317b794cd177674e681321780614a65e073/cotracker/models/core/cotracker/cotracker.py#L146
by
```
 delta = torch.utils.checkpoint.checkpoint(self.updateformer, x, use_reentrant=False)
```
