### ISSUE TITLE
question about windowed inference

### ISSUE THREAD

**Issue by XiaoyuShi97** [facebookresearch/co-tracker#74]
![image](https://github.com/facebookresearch/co-tracker/assets/25840016/2d8c0b71-dc95-484d-a21e-2551ded6c045)

Hi, thanks for sharing this great work. About the windowed inference, I understand that the first T/2 components can be initialized from the last T/2 components from the previous window as overlap exists. But what about the last T/2? Specifically, "copies of the last time t=T/2-1" from P^{(M,1)}", what does it mean?

**Comment by XiaoyuShi97** [comment]
Do you refer to "replicate" mode of padding?

**Comment by nikitakaraevv** [comment]
Hi @XiaoyuShi97, yes, that exactly means the "replicate" padding mode:
https://github.com/facebookresearch/co-tracker/blob/0f9d32869ac51f3bd12c5ead9c206366cfb6caea/cotracker/models/core/cotracker/cotracker.py#L295

**Comment by XiaoyuShi97** [comment]
Now I fully understand this point. It makes sense. Thanks!
