### ISSUE TITLE
Add points as they get visible throughout the video

### ISSUE THREAD

**Issue by Anderstask1** [facebookresearch/co-tracker#78]
Hi,

I wish to add points as the video progresses at inference, at the frame when they get visible. In other words, I wish to initiate the tracking of a set of points where the first visible frame is different for every point. One way to handle this is to restart the model prediction for every new point that gets visible, but then I might loose some temporal information. Is there a good way to handle this?

Thanks for your help!

**Comment by nikitakaraevv** [comment]
Hi @Anderstask1, the model supports this type of tracking. Just choose the corresponding query frame for each point and discard all the predictions before this frame. The model will start tracking from the query frame. Please see section "Tracking manually selected points" in the [Colab demo](https://colab.research.google.com/github/facebookresearch/co-tracker/blob/master/notebooks/demo.ipynb#scrollTo=73d88a5f-057c-4b9f-828d-ee0b97d1e72f) and let me know if you have other questions.

**Comment by Anderstask1** [comment]
Make sense! I did not discard the prediction before the query frame, hence the poor performance.

**Comment by aetaffe** [comment]
@Anderstask1 I am working on the same thing, do you by chance have a code snippet that I can look at? I am using the online model and I restart predictions by setting is_first_step to true every time there is a new point.

**Comment by Anderstask1** [comment]
@aetaffe I set the queries to be a 3-dimensional as stated in the documentation (# - queries. Queried points of shape (1, N, 3) in format (t, x, y) for frame index and pixel coordinates.). I my case, the number of points is fixed, so this step is easy to implement. Here, t is the index of the first visible frame of the respective point, and xy are coordinate values.

**Comment by aetaffe** [comment]
Got it! Thanks @Anderstask1
