### ISSUE TITLE
It seems that the model can not track the balls after they change the direction. 

### ISSUE THREAD

**Issue by LHRYANG** [facebookresearch/co-tracker#89]
Thanks for your awesome work. 

I want to track the ball in a score of the table tennis game. And I provide four queries. As shown in the example, when the ball is from right to left, the model can track the ball correctly. However, after the ball changes its direction, the model fails to continue track. Is there a way to solve this problem?

Thanks for your help!

https://github.com/facebookresearch/co-tracker/assets/22115876/f5b63816-4d2f-42fa-be46-02e15025c324

**Comment by nikitakaraevv** [comment]
Hi @LHRYANG, the model currently resizes every frame to 384 x 512, and operates at this resolution. Thus, a table tennis ball is likely too small for the current model. I would suggest repeating the same experiment after zooming in.

**Comment by LHRYANG** [comment]
After zooming in,  it still does not work...

https://github.com/facebookresearch/co-tracker/assets/22115876/fb1e2565-89f3-4fda-942d-05ff98f83384

**Comment by nikitakaraevv** [comment]
It doesn't work very well, but it's better than in the first video, right? The problem is that the ball is too small for the current model.

**Comment by HsnVahedi** [comment]
> It doesn't work very well, but it's better than in the first video, right? The problem is that the ball is too small for the current model.

Is it possible to train/deploy bigger models to track fast and small objects? assumming we have access to enough GPU
