### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by shersoni610** [facebookresearch/co-tracker#9]
Hello,

How can I run this code on MAC-M1 or cpu? It seems cuda is hardcorded somewhere.

Thanks

**Comment by nikitakaraevv** [comment]
Hi @shersoni610, I've resolved this issue today. Please clone the repo again and let me know if it works. 
Also, now there's an easy way to try the model through `torch.hub`:

```
import torch
import timm
import einops
import tqdm

cotracker = torch.hub.load("facebookresearch/co-tracker", "cotracker_w8")
```

**Comment by shersoni610** [comment]
Thank you very much. I will try again and give you feedback.
