### ISSUE TITLE
Questions about loss computation

### ISSUE THREAD

**Issue by qsisi** [facebookresearch/co-tracker#94]
Hello! @nikitakaraevv 

In the balanced CE loss implementations:
https://github.com/facebookresearch/co-tracker/blob/9ed05317b794cd177674e681321780614a65e073/cotracker/models/core/cotracker/losses.py#L14-L38
For simplicity, assume a 1-d scenario where gt = [1, 0], pred=[p0, p1]∈(0,1), then as computed above:
pos = [1, 0] neg = [0, 1] label = [1, -1]
a = [-p0, p1] b = [0, p1]
loss1 = b + log(exp(-b) + exp(a-b)) = [log(1+exp(-p0)), p1 + log(1+exp(-p1))]
My question is, why not just use this cross-entropy computation:![image](https://github.com/facebookresearch/co-tracker/assets/44374058/ee78ab71-42a6-46b4-b73d-399983f9278b)
then the loss will be like:
loss2 = [-log(p0), -log(1-p1)] ?
What is the difference between these two loss computations? Is the first one better than the second one?

**Comment by qsisi** [comment]
Maybe it's because the first one is smoother than the second one?
![image](https://github.com/facebookresearch/co-tracker/assets/44374058/989711ee-3b31-466c-9bc0-deba326a736c)

**Comment by qsisi** [comment]
let pred==gt, the balanced_ce_loss is not equal to 0:
![image](https://github.com/user-attachments/assets/2e1d5185-d4e8-4ec8-b543-b34c5a79d162)

**Comment by nikitakaraevv** [comment]
Hi @qsisi, that's a great question, thank you!
Yes, this loss is indeed always greater than zero. We've run some experiments and found out that the model converges better with this loss, but we're trying to fix this for the next version.
